package com.personal_game.datn.Backup;

public class Constant {
    public static String token_client = "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJRdWFuZ1N5IiwianRpIjoiMDcyYTIwNzEtNmNmMi00YzUxLWJkODQtYTc3M2VmMTI4MDlhIiwiaWF0IjoiMy8xNy8yMDIyIDU6MTI6NDMgUE0iLCJHcm91cCI6IlF1YW5nU3kiLCJFbWFpbCI6ImNvdmlkMjF0c3BAZ21haWwuY29tIiwiSG9zdGluZyI6ImNvdmlkMjF0c3Auc3BhY2UiLCJQaG9uZSI6ImNsaWVudCIsImV4cCI6MTczMzkxMTk2MywiaXNzIjoiUXVhbmdTeSIsImF1ZCI6IlF1YW5nU3kifQ.jKLDKoVDkNI5cf0lLkzIwPospM6djTq3SwJZTMztPEU";
}
